name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Cache pip dependencies for faster runs
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install langdetect
          pip install flake8 pytest pytest-cov safety

      - name: Lint code
        run: flake8 backend

      - name: Run tests
        run: pytest --cov=backend tests/

      - name: Security check
        run: safety check

      # Optionally upload coverage or test reports
      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/

      # Optional: notify via Slack (requires SLACK_TOKEN secret)
      # - name: Notify Slack
      #   uses: slackapi/slack-github-action@v1.24.0
      #   with:
      #     channel-id: 'C12345678'
      #     slack-token: ${{ secrets.SLACK_TOKEN }}